CREATE DATABASE clinica;

USE clinica;

CREATE TABLE personas(
    ID INT(15) PRIMARY KEY AUTO_INCREMENT,
    PEOPLE_NAME VARCHAR(15) NOT NULL,
    SURNAME VARCHAR(15) NOT NULL,
    SECOND_SURNAME VARCHAR(15),
    DNI VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(15) NOT NULL,
    PHONE INT(15) NOT NULL
);

CREATE TABLE mascotas(
    ID INT(15) PRIMARY KEY AUTO_INCREMENT,
    PET_NAME VARCHAR(15) NOT NULL,
    REIAC VARCHAR(15) NOT NULL,
    ANIMAL_TYPE ENUM('PERRO','GATO','AVE','REPTIL','ROEDOR'),
    BORN_DATE VARCHAR(15) NOT NULL,
    COMENT VARCHAR(30),
    personas_ID INT(15) NOT NULL,
    CONSTRAINT FK_personas_mascotas FOREIGN KEY (personas_ID)
    REFERENCES personas(ID)
);

INSERT INTO personas (PEOPLE_NAME,SURNAME,DNI,EMAIL,PHONE)
VALUES (¨HADRIEL FERNANDO¨,¨QUINTERO¨,¨45151515Z¨,¨hadriel_informatica@icse.es¨,648151515);