CREATE TABLE tASIR (

ID INT(15) PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(15) NOT NULL,
Surname VARCHAR(15)NOT NULL,
DNI VARCHAR(15)NOT NULL UNIQUE,
Email VARCHAR(15)NOT NULL

);

CREATE TABLE docente (

id INT(15) PRIMARY KEY AUTO_INCREMENT
Name VARCHAR(15) NOT NULL,
Surname VARCHAR(15 )NOT NULL,
Email VARCHAR(15) NOT NULL,
Employee_Number INT(15)NOT NULL UNIQUE

);

INSERT INTO DOCENTE ( id, NAME, SURNAME, EMAIL, EMPLOYEE_NUMBER)
VALUES
(1, ¨HADRIEL¨, ¨DE SOMIN¨, ¨GAY@GMAIL.COM¨, 2);