CREATE DATABASE ACTIVIDAD5;

USE ACTIVIDAD5

CREATE TABLE COUNTRY(
ID INT(15) PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(15) NOT NULL UNIQUE,
CONTINENT_ID INT(15) NOT NULL,
CODE INT(15) NOT NULL,
CONSTRAINT FK_COUNTRY_CONTINENT FOREIGN KEY (CONTINENT_ID)
REFERENCES CONTINENT(ID)
);

CREATE TABLE CONTINENT(
ID INT(15) PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(15) NOT NULL UNIQUE
);

INSERT INTO CONTINENT (NAME)
VALUES ('ASIA'),
       ('EUROPE'),
       ('AFRICA'),
       ('NORTH_AMERICA'),
       ('SOUTH_AMERICA');


INSERT INTO COUNTRY (CODE, NAME, CONTINENT_ID)
VALUES (108, 'SPAIN', 2),
       (115, 'ITALY', 2),
       (202, 'ANGOLA', 3),
       (227, 'MALI', 3),
       (407, 'CHINA', 1),
       (415, 'JAPAN', 1),
       (302, 'USA', 4),
       (301, 'CANADA', 4),
       (340, 'ARGENTINA', 5),
       (342, 'BRAZIL', 5);

      DELETE FROM COUNTRY 
      WHERE ID = 1;

      DELETE FROM CONTINENT
      WHERE ID = 3;

