CREATE DATABASE library;

USE library;

CREATE TABLE books(
    ID INT(15) PRIMARY KEY AUTO_INCREMENT,
    BOOK_NAME VARCHAR(50) NOT NULL UNIQUE,
    AUTHOR_NAME VARCHAR(10) NOT NULL,
    EDITORIAL_NAME VARCHAR(10) NOT NULL,
    RELEASE_YEAR INT(15) NULL,
    GENRE ENUM('CIENCE_FICTION','ROMANCE','AUTO_HELPH','TRAVEL','EDUCATIVE') NOT NULL,
    SYNOPSIS VARCHAR(15) NOT NULL,
    BOOK_EDITION DATE,
    ISBN VARCHAR(50) NOT NULL,
    DISPONIBILITY ENUM('DISPONIBLE','STOCK') NOT NULL DEFAULT 'DISPONIBLE'
);

INSERT INTO books(BOOK_NAME,AUTHOR_NAME,EDITORIAL_NAME,GENRE,SYNOPSIS,ISBN,)
VALUES(¨DORAEMON¨,¨NOBITA¨,¨BAMDAI¨,'ROMANCE',¨YES¨,¨115I655201¨),
(¨VALBANERA¨,¨PEPE¨,¨LA EDITORIAL¨,'TRAVEL',¨OKOK¨,¨321456789X¨),
(¨cat 2¨,¨PEPiE¨,¨LA EDITORIAiL¨,'TRAVEL',¨OKOKo¨,¨321456789X¨);

INSERT INTO books(ID,BOOK_NAME,AUTHOR_NAME,EDITORIAL_NAME,RELEASE_YEAR,GENRE,SYNOPSIS,BOOK_EDITION,ISBN,DISPONIBILITY)
VALUES(1,¨NARUTO¨,¨NOBITA¨,¨BAMDAI¨,'ROMANCE',¨NOSE¨,¨115O425201¨);

INSERT INTO books(BOOK_NAME,AUTHOR_NAME,EDITORIAL_NAME,GENRE,SYNOPSIS,ISBN,DISPONIBILITY)
VALUES(¨MESSI¨,¨NOBITA¨,¨BAMDAI¨,'ROMANCE',¨WAWA¨,¨11566559P7¨,'DISPONIBLE');