CREATE DATABASE ICSEHotelDB;

 USE ICSEHotelDB;

CREATE TABLE customer(

ID INT(15) PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(15) NOT NULL,
SURNAME VARCHAR(15) NOT NULL,
BIRTHDATE DATE NOT NULL,
GENDER VARCHAR(15) NOT NULL,
PHONE_NUMBER VARCHAR(15) NOT NULL,
DNI VARCHAR(15) NOT NULL UNIQUE,
ADDRESS VARCHAR(30) NOT NULL,
POSTAL_CODE VARCHAR(15) NOT NULL,
PARKING_REQUIRED ENUM("YES","NO") NOT NULL,
SUGGESTIONS VARCHAR(30),
ROOM_TYPE ENUM("individual","double","family") NOT NULL,
ROOM_NUMBER ENUM("1.1","1.2","1.3","2.1","2.2","2.3") NOT NULL UNIQUE,
PAYMENT_METHOD ENUM("cash","card") NOT NULL,
CHECK_IN_DATE DATE NOT NULL,
CHECK_OUT_DATE DATE NOT NULL,
RESERVATION_NUMBER INT(15) NOT NULL UNIQUE
 
);

